title: Project

files:
  sortable: true

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 3/4

  coverimage:
    label: Cover Image
    type: image
    width: 1/4

  text:
    label: Text
    type:  textarea
